export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Map } from './Map';
export { default as ContactForm } from './ContactForm';
export { default as Quote } from './Quote';
export { default as UnOrderedList } from './UnOrderedList';
export { default as Reviews } from './Reviews';
export { default as SimpleCardsList } from './SimpleCardsList';
export { default as SimpleCard } from './SimpleCard';
// export { default as Gallery } from './Gallery';
// export { default as TabsWithImages } from './TabsWithImages';
